generate test coverage

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -29,3 +29,17 @@ jobs:
     - name: Test
       working-directory: ./string-subsequence
       run: dotnet test --no-build --verbosity normal
+      
+    - name: Test
+      working-directory: ./string-subsequence
+      run: dotnet test --no-build --verbosity normal --configuration Release --logger "trx;LogFileName=test-results.trx" || true
+      
+    - name: Test Report
+      working-directory: ./string-subsequence
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: DotNet Tests            # Name of the check run which will be created
+        path: "**/test-results.trx"    # Path to test results
+        reporter: dotnet-trx        # Format of test results
+        fail-on-error: true
